project:
  type: website
  output-dir: docs

website:
  title: "LY Pechvattana"
  favicon: Image/favicon.png
  navbar:
    left:
      - href: portfolio.qmd
        text: Portfolio

format:
  html:
    theme: Cosmo
    css: styles.css
    toc: true
